# baseURL = "https://your_domain.com/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Power Platform Clinic"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
   name = "Power Platform Clinic"
   headline = "Ask us anything..."
   image = "powerPlatformClinicSmallLogo2.png"  # path relative to static directory

  links = [
    # Custom link


    # { email = "mailto:hello@your_domain.com" },
    # { link = "https://link-to-some-website.com/" },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { bandcamp = "https://username.bandcamp.com" },
    # { bluesky = "https://bsky.app/profile/username" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
     { github = "https://github.com/PowerPlatformClinic" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    # { instagram = "https://instagram.com/username" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://last.fm/user/username" },
    # { linkedin = "https://www.linkedin.com/in/duncanboyne/" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { spotify = "https://spotify.com/user/username" },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { threads = "https://threads.com/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { x = "https://x.com/username" },
     { youtube = "https://youtube.com/@PowerPlatformClinic" },

    { linkedin = { href =  "https://www.linkedin.com/in/duncanboyne/", text = "Duncan Boyne on LinkedIn" } },
    { linkedin = { href =  "https://www.linkedin.com/in/iantweedie/", text = "Ian Tweedie on LinkedIn" } },
    { github = { href = "https://github.com/itweedie", text = "Ian Tweedie on GitHub" } },
    { link = { href = "https://iantweedie.biz/", text = "Ian Tweedie's Link Tree" } },
    { link = { href = "https://techtweedie.github.io/", text = "Tech Tweedie blog"} },
    { link = { href = "https://Mightora.io/", text = "Mightoria.io - Free Power Platform Tools"} },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
